### ISSUE TITLE
No startup? Need to know why or how to correct

### ISSUE THREAD

**Issue by lievenstandaert2** [beademingstoestel/OpenSource_ventilator_lungs#49]
Iif machine (arduino) does not want to start, because of error situation, this is not visible in the GUI. There should be at least a generic error message, confirming machine is connected but something is wrong - with suggested checks/fixes

**Comment by TomBruyneel** [comment]
duplicate of https://github.com/beademingstoestel/OpenSource_ventilator_lungs/issues/46
