### ISSUE TITLE
No pressure alarm when using long Ramp time

### ISSUE THREAD

**Issue by lievenstandaert2** [beademingstoestel/OpenSource_ventilator_lungs#51]
When using a high Ramp time and low inhalation time, i get in a situation where we never reach peak pressure (set value curve is a triangle) eg I/E =1/3 , RR=35, Ramp=0,9
In this situation the low pressure alarm is not triggered, even though we are running below the thresholds.
Not sure if this should be considered a bug or a user asking the machine to do stupid things( you do see on the graphs your settings do not make sense)

**Comment by TomBruyneel** [comment]
I'll make sure you can't select a ramp time that is higher than the inhalation time
