### ISSUE TITLE
Trying to 'calibrate' without plugging in the machine  just tries...

### ISSUE THREAD

**Issue by lievenstandaert2** [beademingstoestel/OpenSource_ventilator_lungs#61]
If I try to calibrate without power, machine should tell me I'm stupid and should plug it in first, not try to calibrate.

**Comment by ThomasVDD** [comment]
Software issue: PC shouldn't allow to press calibrate when receiving init errors

**Comment by TomBruyneel** [comment]
fixed with new dialogs when not connected
