### ISSUE TITLE
Sensor disconnection no longer working correctly

### ISSUE THREAD

**Issue by lievenstandaert2** [beademingstoestel/OpenSource_ventilator_lungs#63]
Disconnecting pressure sensor should mean machine goes into 'safe mode'. This no longer seems to work. Disconnecting the pressure sensor instantly stops the machine. Machine FREEZES ; If oxygen valve is open, it remains open.

Disconnecting flow sensor is not detected. Machine keeps working. Does not go into safe mode?
(does it need to?)  Should definitely give alarm.

**Comment by ThomasVDD** [comment]
Firmware issue - on my todo

**Comment by ThomasVDD** [comment]
Fixed in V3.63
