### ISSUE TITLE
Disconnection of oxygen flow sensor is not detected as alarm

### ISSUE THREAD

**Issue by lievenstandaert2** [beademingstoestel/OpenSource_ventilator_lungs#64]
As it says. Disconnecting the oxygen flow sensor results in the GUI showing FiO2=20% and solenoid keeping on pulsing. Should be a 'sensor failure' alarm.

**Comment by ThomasVDD** [comment]
Firmware issue - on my todo

**Comment by ThomasVDD** [comment]
Fixed in V3.63
